# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - # 'Note: This is a third party action: https://github.com/warrenbuckley/Setup-Nuget'
      uses: warrenbuckley/Setup-Nuget@v1
    - name: NuGet restore
      run: nuget  ${{ env.solution }}
      shell: pwsh
    - name: Build Solution
      run: dotnet build **/*.csproj -c Release
    - name: Create dockerzied WordPress
      shell: bash
    - name: 'Run Tests: Selfhosted WordPress'
      run: dotnet test WordPressPCL.Tests.Selfhosted/WordPressPCL.Tests.Selfhosted.csproj
    - name: Remove Docker containers
      shell: bash
    - name: Create dockerzied WordPress for JWT-Auth Plugin
      shell: bash
